### ISSUE TITLE
Disable web preview on telegram messages

### ISSUE THREAD

**Issue by mhkafadar** [mhkafadar/notifine#22]
Displaying the preview of repo and branch links in every message is unnecessary.

<img width="492" alt="Screenshot 2023-03-18 at 16 53 59" src="https://user-images.githubusercontent.com/43652059/226110322-3c532687-6216-4335-9b20-c3b6e1b77019.png">

**Comment by Rinse12** [comment]
Is this already in production? We still see web preview
