### ISSUE TITLE
How to build the project on Linux

### ISSUE THREAD

**Issue by mbpcoder** [mhkafadar/notifine#26]
Hi @mhkafadar 
I am interested in working on and using this project
please give me some detail on how to build the project on Linux
I don't want to use the docker.

I installed Rust, Build Essentioal, Postgress, and GCC on my machine and got this error
linking with `cc` failed: exit status: 1

**Comment by mhkafadar** [comment]
Hello @mbpcoder,

Thanks for your interest in the project! I will provide a detailed answer on how to build and run the project on Linux without using Docker soon.

**Comment by mhkafadar** [comment]
Hello! @mbpcoder 

I'm using Rust version 1.77.2 on Ubuntu 22.04.

You can set up your environment with these commands:

sudo apt update
sudo apt install build-essential pkg-config libssl-dev libpq-dev ca-certificates -y

Building requires a fair amount of RAM. I recommend having at least 3 GB of RAM or equivalent swap space.
