### ISSUE TITLE
Support for telegram forums?

### ISSUE THREAD

**Issue by Microeinstein** [mhkafadar/notifine#29]
Hi, would it be possible to (configure and) send events to a specific topic in a forum group?

Also it seems that the bot does not work whatsoever in forum groups.

Thanks for your efforts — best regards.

**Comment by mhkafadar** [comment]
Hi @Microeinstein @dismine

Telegram threads (forums) are now supported.

After adding the bot to the group, simply execute the /start command in the thread where you want to receive notifications.
