### ISSUE TITLE
remove Event: "Push Hook", Chat id: 1

### ISSUE THREAD

**Issue by diazzaid** [mhkafadar/notifine#30]
how to remove notifications (Event: "Push Hook", Chat id: 1) ?
<img width="280" alt="image" src="https://github.com/mhkafadar/notifine/assets/25816482/7acee195-1645-4a03-b994-af378b1287b1">

**Comment by mhkafadar** [comment]
@diazzaid 
Hello I will provide an update to remove this message soon.

**Comment by diazzaid** [comment]
> @diazzaid Hello I will provide an update to remove this message soon.

Ok thanks

**Comment by pyhedgehog** [comment]
Don't send them? I mean uncheck following checkbox:
![image](https://github.com/mhkafadar/notifine/assets/1286400/d95b6553-42d5-428c-b772-d2ea34fce642)

**Comment by mhkafadar** [comment]
Hello @diazzaid,
Fixed with the #33

**Comment by diazzaid** [comment]
> Hello @diazzaid, Fixed with the #33

thanks bro

**Comment by diazzaid** [comment]
> Hello @diazzaid, Fixed with the #33

hi bro. 
<img width="166" alt="image" src="https://github.com/mhkafadar/notifine/assets/25816482/0a62193b-c73c-418f-8b69-b974cd5a974b">
<img width="197" alt="image" src="https://github.com/mhkafadar/notifine/assets/25816482/479a245a-d5de-4759-81bb-9484c3cc421e">

I have tried but there is still a notification to admin
