### ISSUE TITLE
How to get GITLAB_TELOXIDE_TOKEN

### ISSUE THREAD

**Issue by raynent** [mhkafadar/notifine#34]
Thanks your bot working fine ,
but if i wanna build it my own
seems this is the most difficult part for noobs like me 
how to get webhook
how to get  GITLAB_TELOXIDE_TOKEN

**Comment by mhkafadar** [comment]
Hey @raynent,

Glad to hear the bot's working well for you!

For setting up the webhook and getting your GITLAB_TELOXIDE_TOKEN, you’ll need to start with Telegram’s BotFather. It’s a bot that Telegram designed to help you create and manage your own bots. Just search for BotFather in Telegram, start a chat with it, and follow the prompts to create a new bot. Once you've set it up, BotFather will give you a token. This is what you’ll use as your GITLAB_TELOXIDE_TOKEN.

Let me know if you need more guidance. Happy to help!
