### ISSUE TITLE
notifine.com links to git_events_bot instead of gitlab_notifine_bot

### ISSUE THREAD

**Issue by IlyaSemenov** [mhkafadar/notifine#35]
As of today, [gitlab_notifine_bot](https://t.me/git_events_bot) doesn't respond on `/start`.

**Comment by IlyaSemenov** [comment]
I digged some more, and the whole thing is odd.

https://notifine.com/ links to "Gitlab bot" under https://t.me/git_events_bot. That bot is down, but, interestingly, its description says "gitlab_notifine_bot". 

https://t.me/gitlab_notifine_bot is also a bot, which is actually running.
However, it gives a webhook URL which responds with 502:

<img width="532" alt="image" src="https://github.com/mhkafadar/notifine/assets/128121/44f4994a-e845-47e8-9371-3559748f3039">

![image](https://github.com/mhkafadar/notifine/assets/128121/cc8b21a8-808a-46e9-8d82-1268aefd2aeb)

which of the following is the legitimate bot? which of it is supposed to work? Is the whole project deprecated perhaps?

**Comment by mhkafadar** [comment]
Thanks for pointing this out. The correct username is gitlab_notifine_bot. Apologies for the confusion – the website is a bit outdated and I'll address that. I've just tested the bot and it's functioning as expected. I’ll add some screenshots for better understanding.

Just a heads-up for your testing: make sure you have at least one real example in your project. For instance, if you're testing for push events, your repo should have at least one commit.

<img width="736" alt="Screenshot 2024-01-21 at 12 27 21" src="https://github.com/mhkafadar/notifine/assets/43652059/7ecaec8c-430f-44cc-80b6-a8a3a86def01">

<img width="381" alt="Screenshot 2024-01-21 at 12 27 04" src="https://github.com/mhkafadar/notifine/assets/43652059/9726555e-8223-4013-b298-15ddee88615b">

<img width="657" alt="Screenshot 2024-01-21 at 12 32 45" src="https://github.com/mhkafadar/notifine/assets/43652059/36154dfd-9ab9-4fe6-9abb-cefc6ca43852">

**Comment by IlyaSemenov** [comment]
Thank you. I see that it indeed does work for certain types of events. However, it doesn't work (crashes with 502) when I press Test > Merge request events even though the README says ✅ Pull request under Gitlab section?

**Comment by mhkafadar** [comment]
Right, the Test > Merge Requests issue is a valid point. It's on my radar now, added to the backlog. But here's a workaround: try manually opening and merging a merge request. This way, you'll receive notifications for both the open and merge events. The merge requests notifications are functioning well.

**Comment by mhkafadar** [comment]
I am closing this issue. Thank you.
