### ISSUE TITLE
Gitlab Pipeline events not actually supported

### ISSUE THREAD

**Issue by IlyaSemenov** [mhkafadar/notifine#36]
README says Gitlab > ✅ Pipeline however that doesn't seem to be so. Pipeline events are not in fact transmitted to Telegram, and the respective source code seems to be completely commented out:

https://github.com/mhkafadar/notifine/blob/45f73065146a0a79aa6ea368330bda207e28ed18/src/webhooks/gitlab/webhook_handlers/pipeline.rs#L40-L45

**Comment by mhkafadar** [comment]
Hi @IlyaSemenov  Regarding pipelines, the bot actually leverages Job events. I intentionally disabled the pipelines section. The reason? To avoid duplicate notifications – one from the job events and another from the pipeline events source, which was happening for the same event.

**Comment by IlyaSemenov** [comment]
Understood, thanks. I suppose a clarification in README would prevent the confusion.

**Comment by mhkafadar** [comment]
Got it, and thanks for the suggestion. Updating the README to clarify this would indeed help prevent any confusion. If you're interested in contributing, how about creating a pull request? Your support on this would be really appreciated.
