### ISSUE TITLE
Escape message text

### ISSUE THREAD

**Issue by IlyaSemenov** [mhkafadar/notifine#55]
Every time a commit has HTML special characters, such as:

```
Blabla

Co-authored-by: Ilya Semenov <ilya@semenov.co>
```

it won't deliver.

**Comment by IlyaSemenov** [comment]
I think you've escaped too much :)

Now the messages became literally like this:

```
<b>Ilya Semenov</b> pushed 1 commit to <a href="https://git.inetss.com/eg11/eg11/tree/master">ЕГ11:master</a>
```

Only the commit text should be escaped, not the entire Telegram message.

**Comment by mhkafadar** [comment]
Hey, apologies for the inconvenience. For now, I’ll be rolling back to the original version. I’ll provide a fix for the commits that include HTML tags within the next 10 days, as I’m currently swamped.

In the meantime, if someone else opens a PR to address this issue, I’d be more than happy to merge it.

Thanks for your understanding!

@IlyaSemenov
